---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-outlet
spec:
  volumes:
  - name: storage
    hostPath:
      path: /mnt/minikube
      type: Directory
  containers:
  - name: kafka-outlet
    image: ghcr.io/build-trust/ockam-kafka-outlet:latest
    env:
      - name: KAFKA_BOOTSTRAP_SERVER
        value: "kafka:9092"
      - name: KAFKA_USE_SSL
        value: "false"
      - name: PROJECT_CONFIG
        value: /mnt/storage/project.json
    volumeMounts:
      ## Provision project info json file via volume mount
      - name: storage
        mountPath: /mnt/storage
        readOnly: false
  - name: ockam-sidecar
    image: ghcr.io/build-trust/ockam:0.87.0
    args: ["node", "create", "-vv", "-f", "--tcp-listener-address=127.0.0.1:4100",
           "--launch-config={\"startup_services\":{\"identity\":{},\"vault\":{},\"verifier\":{}}}",
           "sidecar"]
      env:
        - name: OCKAM_DISABLE_UPGRADE_CHECK
          value: "1"
