---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
spec:
  volumes:
  - name: storage
    hostPath:
      path: /mnt/minikube
      type: Directory
  containers:
  - name: kafka-producer
    image: docker.io/bitnami/kafka:3.4.0-debian-11-r28
    command:
      - sleep
      - infinity
  - name: sidecar
    ## For local-built images
    image: ockam-kafka-sidecar:latest
    imagePullPolicy: Never
    ## For GHCR images
    # image: ghcr.io/build-trust/ockam-kafka-sidecar:latest
    # command:
      # - sleep
      # - infinity
    env:
    - name: ROLE
      value: producer
    - name: BOOTSTRAP_SERVER
      value: 127.0.0.1:9092
    - name: OUTLET_HOST
      value: kafka-outlet
    - name: OUTLET_PORT
      value: "6000"
    - name: ENROLL_TOKEN
      value: /mnt/storage/producer.token
    volumeMounts:
      ## Provision project info json file via volume mount
      - name: storage
        mountPath: /mnt/storage
        readOnly: false


