---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-outlet
  labels:
    app.kubernetes.io/name: kafka-outlet
spec:
  volumes:
  - name: storage
    hostPath:
      path: /mnt/minikube
      type: Directory
  containers:
  - name: kafka-outlet
    ## For local built images
    image: ockam_kafka_outlet:latest
    imagePullPolicy: Never
    ## For GHCR images
    # image: ghcr.io/build-trust/ockam_kafka_outlet:latest
    env:
      - name: KAFKA_BOOTSTRAP_SERVER
        value: "kafka:9092"
      - name: KAFKA_USE_SSL
        value: "false"
      - name: PROJECT_CONFIG
        value: /mnt/storage/project.json
      - name: TCP_PORT
        value: "6000"
    ports:
    - containerPort: 6000
      name: ockam
      protocol: TCP
    volumeMounts:
      ## Provision project info json file via volume mount
      - name: storage
        mountPath: /mnt/storage
        readOnly: false
  - name: ockam-sidecar
    image: ghcr.io/build-trust/ockam:0.87.0
    args: ["node", "create", "-vv", "-f", "--tcp-listener-address=127.0.0.1:4100",
           "--launch-config={\"startup_services\":{\"identity\":{},\"vault\":{},\"verifier\":{}}}", "sidecar"]
    env:
      - name: OCKAM_DISABLE_UPGRADE_CHECK
        value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-outlet
spec:
  selector:
    app.kubernetes.io/name: kafka-outlet
  ports:
    - name: ockam
      protocol: TCP
      port: 6000
      targetPort: ockam


